# Generated by Django 5.0.7 on 2024-07-25 05:00

import fxsimulator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveBigIntegerField(default=fxsimulator.models.current_unix_time)),
                ('price', models.FloatField()),
            ],
        ),
    ]
