# Generated by Django 5.0.7 on 2024-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxsimulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_period',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_period_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_diff',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_final_amount',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_result',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
