# Generated by Django 5.0.7 on 2024-08-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxsimulator', '0002_alter_order_end_period_alter_order_end_period_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
